server:
  port: 9000

spring:
  application:
    name: xingtan-all
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xingtan?useUnicode=true&characterEncoding=utf-8&&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root123

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:loggback.xml
wechat:
  appId: wx20a319eb08aa5e8c
  appSecret: 382f62d773ec085f9ae779b0b1f00244
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=%s
  getTokenUrl: https://api.weixin.qq.com/cgi-bin/token?appid=%s&secret=%s&grant_type=client_credential


