server:
  port: 8011

spring:
  application:
    name:xingtan-account

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xingtan?useUnicode=true&characterEncoding=utf-8&&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root123
