CREATE TABLE IF NOT EXISTS `student` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '用户名',
  `real_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '中文名称',
  `en_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '英文名称',
  `sex` VARCHAR(255) NOT NULL DEFAULT 'SECRECY' COMMENT '性别',
  `birthday` DATE NOT NULL DEFAULT '1970-01-01' COMMENT '生日',
  `telephone` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱',
  `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
  `head_image` TEXT COMMENT '头像',
  `id_card_type` VARCHAR(255) NOT NULL DEFAULT 'IDCARD' COMMENT '证件类型',
  `id_card_no` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '证件号',
  `province` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '省/直辖市',
  `city` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '市',
  `district` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '区',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '其他地址',
  `zip_code` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮编',
  `introduce` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '个人介绍',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否可用',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_name`(`user_name`) USING BTREE ,
  UNIQUE KEY `idx_telephone`(`telephone`) USING BTREE ,
  UNIQUE KEY `idx_email`(`email`) USING BTREE,
  UNIQUE KEY `idx_id_card_no`(`id_card_no`) USING BTREE,
  KEY `idx_birthday`(`birthday`) USING BTREE,
  KEY `idx_sex`(`sex`) USING BTREE,
  KEY `idx_province_city_district`(`province`,`city`,`district`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '学生表';

CREATE TABLE IF NOT EXISTS `teacher` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '用户名',
  `real_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '中文名称',
  `en_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '英文名称',
  `sex` VARCHAR(255) NOT NULL DEFAULT 'SECRECY' COMMENT '性别',
  `birthday` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '生日',
  `telephone` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱',
  `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
  `head_image` TEXT COMMENT '头像',
  `id_card_type` VARCHAR(255) NOT NULL DEFAULT 'IDCARD' COMMENT '证件类型',
  `id_card_no` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '证件号',
  `province` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '省/直辖市',
  `city` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '市',
  `district` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '区',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '其他地址',
  `zip_code` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮编',
  `introduce` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '个人介绍',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否可用',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_name`(`user_name`) USING BTREE ,
  UNIQUE KEY `idx_telephone`(`telephone`) USING BTREE ,
  UNIQUE KEY `idx_email`(`email`) USING BTREE,
  UNIQUE KEY `idx_id_card_no`(`id_card_no`) USING BTREE,
  KEY `idx_birthday`(`birthday`) USING BTREE,
  KEY `idx_sex`(`sex`) USING BTREE,
  KEY `idx_province_city_district`(`province`,`city`,`district`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '教师表';

CREATE TABLE IF NOT EXISTS `organ` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '用户名',
  `real_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '中文名称',
  `en_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '英文名称',
  `sex` VARCHAR(255) NOT NULL DEFAULT 'SECRECY' COMMENT '性别',
  `birthday` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '生日',
  `telephone` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '手机号',
  `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮箱',
  `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
  `head_image` TEXT COMMENT '头像',
  `id_card_type` VARCHAR(255) NOT NULL DEFAULT 'IDCARD' COMMENT '证件类型',
  `id_card_no` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '证件号',
  `province` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '省/直辖市',
  `city` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '市',
  `district` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '区',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '其他地址',
  `zip_code` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '邮编',
  `introduce` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '介绍',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否可用',
  `organ_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '组织名称',
  `organ_code` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '营业执照注册号',
  `build_year` INT NOT NULL DEFAULT 0 COMMENT '创办年份',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_name`(`user_name`) USING BTREE ,
  UNIQUE KEY `idx_telephone`(`telephone`) USING BTREE ,
  UNIQUE KEY `idx_email`(`email`) USING BTREE,
  UNIQUE KEY `idx_id_card_no`(`id_card_no`) USING BTREE,
  KEY `idx_birthday`(`birthday`) USING BTREE,
  KEY `idx_sex`(`sex`) USING BTREE,
  KEY `idx_province_city_district`(`province`,`city`,`district`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '机构表';