server:
  port: 8006
spring:
  application:
    name: xingtan-protal

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    account:
      path: /account/**
      serviceId: xingtan-account
    admin:
      path: /admin/**
      serviceId: xingtan-admin
    account:
      path: /customer/**
      serviceId: xingtan-customer
    account:
      path: /habit/**
      serviceId: xingtan-habit
    account:
      path: /survey/**
      serviceId: xingtan-survey
