server:
  port: 8006
spring:
  application:
    name: xingtan-protal

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    account:
      path: /account/**
      serviceId: xingtan-account
