server:
  port: 8761
spring:
  application:
    name: ek-server

eureka:
  instance:
    hostname: localhost
  server:
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server:port}/eureka/