CREATE TABLE IF NOT EXISTS `habit` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '习惯名称',
  `habit_type_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '类型ID',
  `description` TEXT COMMENT '描述',
  `image` VARCHAR(255) COMMENT '图片',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
  `sex_scope` INT NOT NULL DEFAULT 0 COMMENT '性别范围',
  `age_start` INT NOT NULL DEFAULT 0 COMMENT '年龄开始',
  `age_end` INT NOT NULL DEFAULT 0 COMMENT '年龄结束',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_name`(`name`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '习惯表';

CREATE TABLE IF NOT EXISTS `habit_type` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '名称',
  `description` TEXT COMMENT '描述',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_name`(`name`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '习惯类型表';

CREATE TABLE IF NOT EXISTS `user_habit_record` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '用户ID',
  `habit_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '习惯ID',
  `habit_question_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '习惯问题ID',
  `checked_item_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '选中的选项ID',
  `created_user_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '谁打分',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_habit_question_id`(`user_id`,`habit_id`,`habit_question_id`,`checked_item_id` ) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户习惯分数表';

CREATE TABLE IF NOT EXISTS `user_habit_relation` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '用户ID',
  `habit_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '习惯ID',
  `created_user_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '谁加入',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户习惯关系表';


CREATE TABLE IF NOT EXISTS `habit_question` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL DEFAULT 'SELECT' COMMENT '问题类型',
  `title` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '问题描述',
  `weight` FLOAT(5,1) NOT NULL DEFAULT 1.0 COMMENT '权重',
  `introduce` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '介绍',
  `good` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '好处',
  `bad` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '坏处',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '习惯问题表';

CREATE TABLE IF NOT EXISTS `habit_question_item` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '问题ID',
  `seq` INT NOT NULL DEFAULT 1 COMMENT '序号',
  `seqNo` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '编号',
  `content` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '内容',
  `affect` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '影响',
  `score` INT NOT NULL DEFAULT 0 COMMENT '分数',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_question_id`(`question_id`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '习惯问题选项表';

CREATE TABLE IF NOT EXISTS `habit_question_relation` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `habit_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '习惯ID',
  `question_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '问题ID',
  `gmt_create` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `gmt_modified` DATETIME NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_habit_id`(`habit_id`) USING BTREE,
  KEY `idx_question_id`(`question_id`) USING BTREE,
  UNIQUE KEY `idx_habit_question`(`habit_id`,`question_id`) USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '习惯问题关系表';

